name: Deploy Order Service

on:
  push:
    paths:
      - "order-service/**"   # Triggered only when user-service code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push User Service Image
        run: |
          IMAGE_URI="${{ secrets.ECR_URI }}/user-service:latest"
          docker build -t $IMAGE_URI ./user-service
          docker push $IMAGE_URI

      - name: Update Task Definition
        run: |
          sed -i 's#<IMAGE_URI>#${{ secrets.ECR_URI }}/user-service:latest#g' ./user-service/task-def.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./user-service/task-def.json
          service: order-service
          cluster: my-cluster
          wait-for-service-stability: true
