name: Deploy User Service

on:
  push:
    paths:
      - "user-service/**"   # Triggered only when user-service code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: false
          registry-type: private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }} # 'ap-south-1' Set AWS Region explicitly

      - name: Build and Push User Service Image
        run: |
          IMAGE_URI="${{ secrets.ECR_URI }}/user-service:latest"
          docker build -t $IMAGE_URI ./user-service
          docker push $IMAGE_URI

      - name: Update Task Definition
        run: |
          sed -i 's#<IMAGE_URI>#${{ secrets.ECR_URI }}/user-service:latest#g' ./user-service/task-def.json

      - name: Register Task Definition (if not already registered)
        run: |
          aws ecs register-task-definition \
            --family user-service \
            --container-definitions "file://./user-service/task-def.json" \
            --region ap-south-1

      - name: Create ECS Service (if not already created)
        run: |
          aws ecs create-service \
            --cluster my-microservices \
            --service-name user-service \
            --task-definition user-service:1 \
            --desired-count 1 \
            --launch-type EC2 \
            --region ap-south-1

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./user-service/task-def.json
          service: user-service
          cluster: my-microservices
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
