name: Deploy User Service
 
on:
  push:
    paths:
      - "user-service1/**"   # Triggered only when user-service code changes
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2
 
      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: false
          registry-type: private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }} # 'ap-south-1' Set AWS Region explicitly
 
      - name: Build and Push User Service Image
        run: |
          IMAGE_URI="${{ secrets.ECR_URI }}/user-service:latest"
          docker build -t $IMAGE_URI ./user-service
          docker push $IMAGE_URI
 
      - name: Update Task Definition
        run: |
          sed -i 's#<IMAGE_URI>#${{ secrets.ECR_URI }}/user-service:latest#g' ./user-service/task-def.json
 
      - name: Attach CloudWatch Logs Permissions to Task Execution Role
        run: |
          aws iam attach-role-policy \
            --role-name ecsTaskExecutionRole \
            --policy-arn arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://./user-service/task-def.json \
            --region ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }} # 'ap-south-1' Set AWS Region explicitly
 
      - name: Check if Service Exists
        id: check-service
        run: |
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster my-microservices \
            --services user-service \
            --query 'services[0].status' \
            --output text --region ap-south-1)
          echo "Service Status: $SERVICE_STATUS"
          if [[ "$SERVICE_STATUS" == "ACTIVE" ]]; then
            echo "Service exists, preparing for update."
            echo "::set-output name=service-exists::true"
          else
            echo "Service does not exist, will create a new one."
            echo "::set-output name=service-exists::false"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
 
      - name: Create or Update ECS Service
        run: |
          if [ "${{ steps.check-service.outputs.service-exists }}" == "true" ]; then
            echo "Updating ECS service..."
            aws ecs update-service \
              --cluster my-microservices \
              --service user-service \
              --task-definition user-service:1 \
              --desired-count 1 \
              --region ap-south-1
          else
            echo "Creating ECS service..."
            aws ecs create-service \
              --cluster my-microservices \
              --service-name user-service \
              --task-definition user-service:1 \
              --desired-count 1 \
              --launch-type EC2 \
              --region ap-south-1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }} # Set AWS Region explicitly
 
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./user-service/task-def.json
          service: user-service
          cluster: my-microservices
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
