name: Deploy User Service

on:
  push:
    paths:
      - "user-service/**"   # Triggered only when user-service code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for building multi-platform images
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: false
          registry-type: private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

      # Step 4: Build the Docker image and push it to ECR
      - name: Build and Push User Service Image
        run: |
          IMAGE_URI="${{ secrets.ECR_URI }}/user-service:latest"
          docker build -t $IMAGE_URI ./user-service
          docker push $IMAGE_URI

     # Step 5: Update Task Definition (Create a new revision with the updated image URI)
      - name: Update Task Definition
        run: |
          sed -i 's#<IMAGE_URI>#${{ secrets.ECR_URI }}/user-service:latest#g' ./user-service/task-def.json
          # Register new task definition
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://./user-service/task-def.json \
            --region ap-south-1 --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "Registered new task definition: $TASK_DEFINITION_ARN"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1


      # Step 6: Attach CloudWatch Logs permissions to ECS Task Execution Role
      - name: Attach CloudWatch Logs Permissions to Task Execution Role
        run: |
          aws iam attach-role-policy \
            --role-name ecsTaskExecutionRole \
            --policy-arn arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

      # Step 7: Register the updated task definition to ECS
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://./user-service/task-def.json \
            --region ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

      # Step 8: Check if the ECS service already exists
      - name: Check if Service Exists
        id: check-service
        run: |
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster my-microservices \
            --services user-service \
            --query 'services[0].status' \
            --output text --region ap-south-1)
          echo "Service Status: $SERVICE_STATUS"
          if [[ "$SERVICE_STATUS" == "ACTIVE" ]]; then
            echo "Service exists, preparing for update."
            echo "::set-output name=service-exists::true"
          else
            echo "Service does not exist, will create a new one."
            echo "::set-output name=service-exists::false"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

            # Step 9 - Create or Update ECS Service with ALB
      - name: Create or Update ECS Service with ALB
        run: |
          if [ "true" == "true" ]; then
            echo "Updating ECS service with ALB..."
        
            # Ensure that $TASK_DEFINITION_ARN is passed and not empty
            if [[ -n "$TASK_DEFINITION_ARN" ]]; then
                # ECS Update Service
                aws ecs update-service \
                  --cluster my-microservices \  # Define your ECS cluster
                  --service user-service \      # Specify the ECS service to update
                  --task-definition "$TASK_DEFINITION_ARN" \  # Specify the task definition ARN for the service
                  --desired-count 1 \           # Desired number of service tasks
                  --load-balancers '[{"targetGroupArn":"arn:aws:elasticloadbalancing:ap-south-1:980921736494:targetgroup/ecs-tg/37c661d494e4ce68","containerName":"user-service","containerPort":3000}]' \
                  --region ap-south-1 \         # Specify the AWS region
                  --force-new-deployment        # Ensure a fresh deployment for service update
          
            else
                echo "Error: TASK_DEFINITION_ARN is empty. Please set the Task Definition ARN."
                exit 1
            fi
        else
            echo "Creating ECS service with ALB..."
            
            # ECS Create Service if the above condition is false
            aws ecs create-service \
              --cluster my-microservices \         # Define your ECS cluster
              --service-name user-service \        # Define the ECS service name to create
              --task-definition "$TASK_DEFINITION_ARN" \   # Specify the Task Definition ARN
              --desired-count 1 \                  # Number of tasks for service
              --launch-type EC2 \                  # EC2 launch type, adjust according to your setup (FARGATE or EC2)
              --load-balancers '[{"targetGroupArn":"arn:aws:elasticloadbalancing:ap-south-1:980921736494:targetgroup/ecs-tg/37c661d494e4ce68","containerName":"user-service","containerPort":3000}]' \ 
              --region ap-south-1 \                # Define AWS region (India in this case)
              --health-check-grace-period-seconds 60   # Optional, ensure grace period on health check for slow start
        
            # The creation command ensures the new service is provisioned and associated with the load balancer (ALB).
        fi
      
      
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1



      # Step 10: Verify Target Registration in ALB Target Group
      - name: Verify Targets in ALB Target Group
        run: |
          echo "Checking target registration status in ALB target group..."
          aws elbv2 describe-target-health \
            --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:980921736494:targetgroup/ecs-tg/37c661d494e4ce68 \
            --region ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1

      # # Step 11: Register Missing Targets (if needed)
      # - name: Register Targets Manually
      #   run: |
      #     INSTANCE_ID=$(aws ec2 describe-instances \
      #       --filters "Name=tag:Name,Values=your-ecs-instance-tag" \
      #       --query "Reservations[].Instances[].InstanceId" \
      #       --output text --region ap-south-1)
      #     PORT=3000
      #     aws elbv2 register-targets \
      #       --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:980921736494:targetgroup/ecs-tg/37c661d494e4ce68 \
      #       --targets Id=$INSTANCE_ID,Port=$PORT \
      #       --region ap-south-1
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ap-south-1
